# Experiment 7
# Vedant Gadge D115 60009230120 D2-2

In [3]:
import numpy as np

### 1. Create a 3x3 matrix of random integers between 1 and 10 and find the total sum of its elements.

In [22]:
array = np.random.randint(1,11,size=(3,3))
print(array)
print('The sum is: ',np.sum(array))

[[ 8  3  6]
 [ 4  3  3]
 [ 5  6 10]]
The sum is:  48


### 2. Generate a 4x4 matrix of random numbers and compute the average of all its elements.

In [10]:
array = np.random.randint(11,size=(4,4))
print(array)
print('The average is: ',np.mean(array))

[[ 9 10  0  2]
 [ 1  5  1  6]
 [ 3  9  8 10]
 [ 7  8  7  3]]
The average is:  5.5625


### 3. Create a 2x3 matrix and find the sum of all elements in the second row

In [16]:
array = np.random.randint(11,size=(2,3))
print(array)
print('The sum of elements in second row is: ',np.sum(array,axis = 1)[1])  
#np.sum(array,axis = 1) returns a new array which consists the sum of each row , we want just the second row so we use [1]

[[1 2 5]
 [1 4 8]]
The sum of elements in second row is:  13


### 4. Generate a 5x5 matrix of random integers and determine the highest value in each column

In [21]:
array = np.random.randint(11,size=(5,5))
print(array)
print('The max element in each column is: ',np.max(array,axis = 0))

[[ 8  4  2  6 10]
 [10  0  9  1  4]
 [ 2  8  1  7  5]
 [10  5  9  0  1]
 [10  3  9  6  6]]
The max element in each column is:  [10  8  9  7 10]


### 5. Create a 4x4 matrix and calculate the sum of its main diagonal elements.

In [25]:
array = np.random.randint(11,size=(4,4))
print(array)
print('The sum of elements in the diagonal is: ',np.matrix(array).diagonal().sum())

[[7 4 4 9]
 [7 8 9 6]
 [6 8 4 1]
 [0 3 2 6]]
The sum of elements in the diagonal is:  25


### 6. Generate a 3x3 matrix and find the smallest value among all its elements,

In [27]:
array = np.random.randint(11,size=(3,3))
print(array)
print('The min element in each column is: ',np.min(array))

[[ 2 10  1]
 [ 3  0  5]
 [10 10  8]]
The min element in each column is:  0


### 7. Create a 4x4 matrix of random integers between 1 and 20 and compute the sum of all elements that are greater than 10.

In [29]:
array = np.random.randint(1,20,size=(4,4))
print(array)
print('The sum of elements in second row is: ',np.sum(array[array>10]))

[[18  1 14 10]
 [ 9 17  9  3]
 [ 2 15  7  8]
 [ 9 16  2 19]]
The sum of elements in second row is:  99


### 8. Generate a 5x5 matrix of random numbers and find the mean of the maximum values of each row.

In [7]:
array = np.random.randint(11,size=(5,5))
print(array)
print('The mean of max element in each row is: ',np.mean(np.max(array,axis = 1)))

[[2 4 2 9 9]
 [8 4 9 3 5]
 [6 4 8 8 1]
 [9 7 7 5 1]
 [1 9 0 7 9]]
The mean of max element in each row is:  8.8


### 9. Create a 3x3 matrix and calculate the difference between the sum of the elements in the first row and the sum of the elements in the last row.

In [9]:
array = np.random.randint(11,size=(3,3))
print(array)
print('The difference between the sum of the elements in the first row and the sum of the elements in the last row: ',abs(np.sum(array, axis = 1)[0] - np.sum(array, axis = 1)[2]))

[[7 6 7]
 [0 5 4]
 [2 0 4]]
The difference between the sum of the elements in the first row and the sum of the elements in the last row:  14


### 10. Generate a 6x6 matrix of random integers and replace all values below the median with zero.

In [20]:
array = np.random.randint(11,size=(6,6))
print(array,end = '\n\n')
print('The median of the array is: ',np.median(array),end = '\n\n')
array[array<np.median(array)] = 0
print(array)

[[ 4  2  3  8  6  2]
 [ 2  1  3  2  6  6]
 [ 9  2  5  0  4  6]
 [ 3  2  9  9  3  9]
 [ 6  2  1  2  8  3]
 [10  2  7  7  9  4]]

The median of the array is:  4.0

[[ 4  0  0  8  6  0]
 [ 0  0  0  0  6  6]
 [ 9  0  5  0  4  6]
 [ 0  0  9  9  0  9]
 [ 6  0  0  0  8  0]
 [10  0  7  7  9  4]]


### 11. Create a 4x4 matrix and compute the sum of elements in the upper triangular part of the matrix.

In [23]:
array = np.random.randint(11,size=(4,4))
print(array)
print('The median of the array is: ',np.sum(np.triu(array)))

[[ 3  7  5  6]
 [ 4  7  0  9]
 [ 2  1 10  9]
 [ 1  4  0  7]]
The median of the array is:  63


### 12. Generate a 3x4 matrix of random values and find the standard deviation of the elements in the third column.

In [26]:
array = np.random.randint(11,size=(3,4))
print(array)
print('The standard deviation of elements of 3rd column is: ',np.std(array, axis=0)[2])

[[ 6  9  2  1]
 [ 4  5  8 10]
 [ 1  4  4 10]]
The standard deviation of elements of 3rd column is:  2.494438257849294
