# Experiment 8
# D115 Vedant Gadge 60009230120

In [17]:
import numpy as np
from scipy import stats

### 1. Calculate the mean of an array of numbers [3, 6, 9,12, 15].

In [18]:
array = [3,6,9,12,15]
print(array)
print("Mean of the array is: ",np.mean(array))

[3, 6, 9, 12, 15]
Mean of the array is:  9.0


### 2. Determine the median of an array of numbers [7, 3, 9, 1, 5].

In [19]:
array = [7,3,9,1,5]
print(array)
print("Median of the array is: ",np.median(array))

[7, 3, 9, 1, 5]
Median of the array is:  5.0


### 3. Find the mode of an array of integers [4, 1, 2, 2, 3, 4, 4].

In [20]:
array = [4,1,2,2,3,4,4]
print(array)
print("Mode of the array is: ",stats.mode(array)[0]) 
#numpy doesnt have mode , so we use scipy instead
#scipy.mode() returns an array of two elements => [mode , no. of times mode has occurred]

[4, 1, 2, 2, 3, 4, 4]
Mode of the array is:  4


### 4. Compute the variance of an array of numbers [2, 4, 4, 4, 5, 5, 7, 9].

In [21]:
array = [2,4,4,4,5,5,7,9]
print(array)
print("Variance of the array is: ",np.var(array)) 

[2, 4, 4, 4, 5, 5, 7, 9]
Variance of the array is:  4.0


### 5. Calculate the standard deviation of an array of numbers [10, 12, 23, 23, 16, 23, 21, 16].

In [22]:
array = [10,12,23,23,16,23,21,16]
print(array)
print("Standard Deviation of the elements in the array is: ",np.std(array))

[10, 12, 23, 23, 16, 23, 21, 16]
Standard Deviation of the elements in the array is:  4.898979485566356


### 6. Determine the range of an array of numbers [3, 7, 8, 5, 12, 14, 21, 13, 18].

In [23]:
array = [3,7,8,5,12,14,21,13,18]
print(array)
print("Range of the array is: ",np.max(array)-np.min(array)) 

[3, 7, 8, 5, 12, 14, 21, 13, 18]
Range of the array is:  18


### 7. Compute the Pearson correlation coefficient between two arrays [1, 2, 3, 4, 5] and [2, 4, 6, 8, 10].

In [24]:
array1 = [1,2,3,4,5]
array2 = [2,4,6,8,10]
print("The Pearson correlation coefficient of the two arrays is: ",np.corrcoef(array1,array2)) 

The Pearson correlation coefficient of the two arrays is:  1.0


### 8. Create an array of 20 zeros.

In [25]:
print("An array with 20 zeroes: ", np.zeros(20 , dtype = int))

An array with 20 zeroes:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


### 9. Generate a 4x4 identity m

In [26]:
print("An array with 20 zeroes: \n", np.identity(4 , dtype = int))

An array with 20 zeroes: 
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


### 10. Calculate the dot product of arrays [1, 2, 3] and [4, 5, 6].

In [27]:
array1 = [1,2,3]
array2 = [4,5,6]
print("The dot product of the two arrays is: ",np.dot(array1,array2)) 

The dot product of the two arrays is:  32


### 11. Reshape an array of 12 elements into a 3x4.

In [28]:
array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12]
print("The dot product of the two arrays is: \n",np.reshape(array,(3,4)))

The dot product of the two arrays is: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### 12. Manually compute the Pearson correlation coefficient between two arrays [1, 2, 3, 5] and [2, 3, 4, 6] using the formula.

In [31]:
x = np.array([1, 2, 3, 5])
y = np.array([2, 3, 4, 6])

n = len(x)

sum_x = np.sum(x)
sum_y = np.sum(y)
sum_xy = np.sum(x * y)
sum_x_squared = np.sum(x ** 2)
sum_y_squared = np.sum(y ** 2)

numerator = n * sum_xy - sum_x * sum_y
denominator = np.sqrt((n * sum_x_squared - sum_x ** 2) * (n * sum_y_squared - sum_y ** 2))

correlation_coefficient = numerator / denominator
print(f"Pearson Correlation Coefficient: {correlation_coefficient}")

Pearson Correlation Coefficient: 1.0
