# Experiment 7
# Vedant Gadge D115 60009230120 D2-2

In [1]:
import numpy as np

In [22]:
array = np.random.randint(1,11,size=(3,3))
print(array)
print('The sum is: ',np.sum(array))

[[ 8  3  6]
 [ 4  3  3]
 [ 5  6 10]]
The sum is:  48


In [10]:
array = np.random.randint(11,size=(4,4))
print(array)
print('The average is: ',np.mean(array))

[[ 9 10  0  2]
 [ 1  5  1  6]
 [ 3  9  8 10]
 [ 7  8  7  3]]
The average is:  5.5625


In [16]:
array = np.random.randint(11,size=(2,3))
print(array)
print('The sum of elements in second row is: ',np.sum(array,axis = 1)[1])  
#np.sum(array,axis = 1) returns a new array which consists the sum of each row , we want just the second row so we use [1]

[[1 2 5]
 [1 4 8]]
The sum of elements in second row is:  13


In [21]:
array = np.random.randint(11,size=(5,5))
print(array)
print('The max element in each column is: ',np.max(array,axis = 0))

[[ 8  4  2  6 10]
 [10  0  9  1  4]
 [ 2  8  1  7  5]
 [10  5  9  0  1]
 [10  3  9  6  6]]
The max element in each column is:  [10  8  9  7 10]


In [25]:
array = np.random.randint(11,size=(4,4))
print(array)
print('The sum of elements in the diagonal is: ',np.matrix(array).diagonal().sum())

[[7 4 4 9]
 [7 8 9 6]
 [6 8 4 1]
 [0 3 2 6]]
The sum of elements in the diagonal is:  25


In [27]:
array = np.random.randint(11,size=(3,3))
print(array)
print('The min element in each column is: ',np.min(array))

[[ 2 10  1]
 [ 3  0  5]
 [10 10  8]]
The min element in each column is:  0


In [29]:
array = np.random.randint(1,20,size=(4,4))
print(array)
print('The sum of elements in second row is: ',np.sum(array[array>10]))

[[18  1 14 10]
 [ 9 17  9  3]
 [ 2 15  7  8]
 [ 9 16  2 19]]
The sum of elements in second row is:  99


In [33]:
array = np.random.randint(11,size=(5,5))
print(array)
print('The mean of max element in each row is: ',np.mean(np.max(array,axis = 1)))

[[ 8  8  6  6  8]
 [ 8  2 10  5  0]
 [ 0  0 10  9  4]
 [10  0  9  7  4]
 [ 0  2  8  7  5]]
The mean of max element in each row is:  9.2
